FROM stackbrew/fedora:20

RUN yum -y install fedora-packager git wget python-devel
RUN rpmdev-setuptree
RUN mkdir /build
WORKDIR /build
RUN git clone https://github.com/jayofdoom/cloud-init-fedora-pkg
WORKDIR cloud-init-fedora-pkg
RUN cp * /rpmbuild/SOURCES/
RUN wget -O /rpmbuild/SOURCES/cloud-init-0.7.5.tar.gz https://launchpad.net/cloud-init/trunk/0.7.5/+download/cloud-init-0.7.5.tar.gz
RUN rpmbuild -bb cloud-init.spec
